[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from   = "/embed.js"
  to     = "/embed.js"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200